version: '3.7'

services:

  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on: 
      - web-api
      - web-front
    networks:
      - default-bridge

  web-api:
    build:
      dockerfile: Dockerfile.test
    container_name: WSGI-flask-web-api
    volumes: 
      - ./flask/migrations/postgres:/usr/app/migrations
    ports:
      - "${TEST_SERVER_PORT}:5000"
    environment:
      - APP_CONFIG_FILE=/usr/app/settings/test.py
    
  web-front:
    container_name: test-web-front
    ports:
      - "${TEST_FRONT_PORT}:3000"

  db:
    container_name: postgres-db
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - "${POST_DB_PORT}:5432"
    networks:
      default-bridge:
        ipv4_address: 172.16.5.7

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "${PROMETHEUS_PORT}:9090"
  #   volumes:
  #     - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
