version: '3.7'

services:
  web-api:
    build:
      dockerfile: Dockerfile.dev
    container_name: dev-flask-web-api
    volumes:
      - ./flask:/usr/app
    environment:
      - APP_CONFIG_FILE=/usr/app/settings/local.py
    ports:
      - "${DEV_SERVER_PORT}:5000"
    
  next-front:
    container_name: dev-front-web
    ports:
      - "${DEV_FRONT_PORT}:3000"

networks:
  app-net:
    name: dev-net
