version: '3.7'

services:
  web-api:
    build:
      dockerfile: Dockerfile.test
    container_name: WSGI-flask-web-api
    volumes: 
      - ./flask/migrations/postgres:/usr/app/migrations
    ports:
      - "${TEST_SERVER_PORT}:5000"
    environment:
      - APP_CONFIG_FILE=/usr/app/settings/test.py
    
  next-front:
    container_name: test-front-web
    ports:
      - "${TEST_FRONT_PORT}:3000"

  db:
    container_name: postgres-db
    image: postgres:15.3
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: unless-stopped
    ports:
      - "${POST_DB_PORT}:5432"
    networks:
      - app-net

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "${PROMETHEUS_PORT}:9090"
  #   volumes:
  #     - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  app-net:
    name: test-net