version: '3.7'

services:
  flask-server:
    ports:
      - "${TEST_SERVER_PORT}:5000"
    restart: on-failure
    secrets:
      - source: postgres-connection
        target: /usr/app/secrets.json
    depends_on:
      - db
    
  next-front:
    ports:
      - "${TEST_FRONT_PORT}:3000"
    restart: on-failure

  db:
    container_name: postgres-db
    image: postgres:15.3
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: unless-stopped
    ports:
      - "${TEST_DB_PORT}:5432"
    networks:
      - app-net

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "${PROMETHEUS_PORT}:9090"
  #   volumes:
  #     - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  app-net:
    name: test-net