version: '3.7'

services:

  web-api:
    build:  
      context: ./flask
    secrets:
      - source: postgres-connection
        target: /usr/app/secrets.json
    networks:
      - default-bridge


  web-front:
    build:
      context: ./react-front
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/app/node_modules
      - ./react-front:/usr/app
    depends_on:
      - web-api
    networks:
      - default-bridge

secrets:
  postgres-connection:
    file: ./configs/postgres/secrets.json

networks:
  default-bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.16.5.0/20
