version: '3.7'

services:
  web-api:
    build:
      dockerfile: Dockerfile.dev
    container_name: dev-flask-web-api
    volumes:
      - ./flask:/usr/app
      - ./flask/migrations/sqlite:/usr/app/migrations
    environment:
      - APP_CONFIG_FILE=/usr/app/settings/local.py
    ports:
      - "${DEV_SERVER_PORT}:5000"
    
  next-front:
    container_name: dev-front-web
    ports:
      - "${DEV_FRONT_PORT}:3000"

  jenkins-blueocean-master:
    container_name: jenkins-master
    
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/master:/var/jenkins_home
    restart: on-failure
    privileged: true
    networks:
      - app-net

networks:
  app-net:
    name: dev-net
