version: '3.7'

services:
  flask-server:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "${DEV_SERVER_PORT}:5000"
    
  next-front:
    ports:
      - "${DEV_FRONT_PORT}:3000"

networks:
  app-net:
    name: dev-net
