FROM ubuntu:20.04 AS builder-image

# avoid user interaction
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y python3.9 python3.9-dev python3.9-venv python3-pip python3-wheel build-essential && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# package management
RUN python3.9 -m venv /usr/app/flask/venv
ENV PATH="/usr/app/flask/venv/bin:$PATH"

# install requirements
COPY flask/requirements.txt .
RUN pip3 install --no-cache-dir wheel
RUN pip3 install --no-cache-dir -r requirements.txt

FROM ubuntu:20.04 AS runner-image

RUN apt-get update && apt-get install --no-install-recommends -y python3.9 python3-venv && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# use gunicorn WSGI

RUN useradd --create-home myuser
WORKDIR /usr/app/flask

COPY --from=builder-image usr/app/flask/venv ./venv
USER myuser

COPY ./flask .

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# activate virtual environment
ENV VIRTUAL_ENV=/usr/app/flask/venv
ENV PATH="/usr/app/flask/venv/bin:$PATH"

CMD ["gunicorn","-w","2","--bind","0.0.0.0:5000", "wsgi:app"]

